### ISSUE TITLE
Hello, Albert

### ISSUE THREAD

**Issue by jsgrahamus** [enku/teamplayer#1]
I used to work with an Albert Hopkins at LabCorp in the Dallas area between 1996 and 2006, and he just loved Python.  I wonder if you are the same individual.

Steve Graham (jsgrahamus@yahoo.com)

**Comment by enku** [comment]
Hello Steve.  Yes, that's me. Sorry I didn't see this post earlier. It was hidden away and I never check issues here (I've never received any). How are things with you?
